/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ZLHW.base.Form;


/**
 * MyEclipse Struts Creation date: 05-13-2010
 * 
 * XDoclet definition:
 * 
 * @struts.form name="loginForm"
 */
public class FuzzySearchForm extends BaseForm {
	protected String orderField = ""; // 排序查询用的字段名
	protected String searchField = ""; // 模糊查询的字段名
	private String searchedId = ""; // 模糊查询的关键字
	public String getOrderField(){
		 return this.orderField;
		}

		public void setOrderField(String orderField){
		 this.orderField = orderField;
		}

		public String getSearchField(){
		 return this.searchField;
		}

		public void setSearchField(String searchField){
		 this.searchField = searchField;
		}

		public String getSearchedId(){
		 return this.searchedId;
		}

		public void setSearchedId(String searchedId){
		 this.searchedId = searchedId;
		}



}