/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ZLHW.base.Form;


/**
 * MyEclipse Struts Creation date: 05-13-2010
 * 
 * XDoclet definition:
 * 
 * @struts.form name="loginForm"
 */
public class PageForm extends BaseForm {
	protected int pageNum = 1; // 表示当前请求的分页号
	protected int numPerPage = 20; // 每页行数
	
	public int getStartLine() {
		return pageNum*numPerPage-pageNum;
	}

	public int getPageNum() {
		return this.pageNum;
	}

	public void setPageNum(int pageNum) {
		this.pageNum = pageNum;
	}

	public int getNumPerPage() {
		return this.numPerPage;
	}

	public void setNumPerPage(int numPerPage) {
		this.numPerPage = numPerPage;
	}

}